### ISSUE TITLE
The URL for the whole pororo video clips is not available. Could you please give me the video clips. Thanks

### ISSUE THREAD

**Issue by girmaji08** [Kyung-Min/PororoQA#3]
Hi. The URL for the pororo video clips is not available. The URL provided does not point to the videos. Could you please give me the video clips.My Email ID : grohit90@gmail.com .
Thanks

**Comment by ddemszky** [comment]
Hi, I'd also like to use the videos -- could you please email me (ddemszky@stanford.edu)? Thanks!

**Comment by Zhihang-Li** [comment]
I also want to use videos, could you share me 603939993@qq.com

**Comment by Kyung-Min** [comment]
Sorry for late reply. I will fix it soon

**Comment by Kyung-Min** [comment]
Please check it once again. Thanks!
