### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by e-bug** [Kyung-Min/PororoQA#4]
Hi!

Could you please add license information (e.g., [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)) for the video clips and descriptions to make sure we can use them?

Thank you!
Emanuele

**Comment by Kyung-Min** [comment]
Hi, thanks for your question.

You can freely use the dataset only for research purpose. However, redistribution and sharing are not permitted.

Thanks!
Kim
